ServicesUrl:
    PolicyApiUrl: http://Microservices.Demo.Policy.Api/api/policies
    ProductApiUrl: http://Microservices.Demo.Product.API/api/products
ElasticApm:
    SecretToken: 
    ServerUrls: http://microservices.demo.apm-server:8200
    ServiceName: Microservices.Demo.Report
    Environment: production